---
- hosts: localhost
  remote_user: jd
  vars:
    ruby_version: ruby-2.1.5
  tasks:
  - name: install media packages
    sudo: yes
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - gimp
      - vlc
      - audacious
      # - kazam
  - name: install dev packages
    sudo: yes
    apt: name={{ item }} state=latest
    with_items:
      - build-essential
      - curl
      - wget
      - openjdk-7-jdk
      - icedtea-7-plugin
      - git
      - subversion
      - vim-gtk
      - terminator
      - meld
      - gitg
      - patch
      - zlib1g-dev
      - liblzma-dev
      - ruby-dev
      - libsqlite3-dev
      - cmake
      - python3
      - python3-pip
      - nodejs
      - virtualbox
      - exuberant-ctags
      - htop
      - libpq-dev
      - libc6:i386
      - libncurses5:i386
      - libstdc++6:i386
      - lib32z1
      - libbz2-1.0:i386
      - openssl
      - readline-common
      - bzip2
      - make
      - libssl-dev
      - libbz2-dev
      - libreadline-dev
      - llvm
      - libncurses5-dev
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - silversearcher-ag
  - name: ensure openjdk 6 is absent
    sudo: yes
    apt: name=openjdk-6-jdk state=absent
  - name: ensure icedtea 6 is absent
    sudo: yes
    apt: name=icedtea-6-plugin state=absent
  - name: install other packages
    sudo: yes
    apt: name={{ item }} state=latest
    with_items:
      - xchat
      - pidgin
      - libreoffice
      - gdebi
      - unzip
      - synaptic
      - conky
      - cryptsetup
      - xclip
  - name: install opencv packages
    sudo: yes
    apt: name={{ item }} state=latest
    with_items:
      - pkg-config
      - libjpeg8-dev
      - libtiff5-dev
      - libjasper-dev
      - libpng-dev
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - libv4l-dev
      - libxvidcore-dev
      - libx264-dev
      - libgtk-3-dev
      - libatlas-base-dev
      - gfortran
      - python3.5-dev
  - name: copy gitconfig
    copy: src=files/gitconfig dest=~/.gitconfig mode=0664 force=yes
  - name: copy git commit template message
    copy: src=files/git_commit_message_template dest=~/.git_commit_message_template mode=0664 force=yes
  - name: copy conkyrc
    copy: src=files/conkyrc dest=~/.conkyrc mode=0664
  - name: copy gemrc
    copy: src=files/gemrc dest=~/.gemrc mode=0664
  - name: copy vimrc
    copy: src=files/vimrc dest=~/.vimrc mode=0664
  - name: copy fonts folder
    copy: src=files/fonts/ dest=~/.fonts mode=0775 force=yes
  - name: clone gvim vundle plugin
    git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim
  - name: reload the cache of fonts
    sudo: yes
    shell: fc-cache -fv
  - name: copy scripts folder
    copy: src=files/scripts/ dest=~/scripts mode=0775 force=yes
  - name: copy sublime text 3 preferences folder
    copy: src=files/sublime/ dest=~/.config/sublime-text-3/Packages/User mode=0775 force=no
  - name: copy sublime text 3 package manager
    copy: src=files/sublime/Package Control.sublime-package dest=~/.config/sublime-text-3/Installed Packages/Package Control.sublime-package mode=0775 force=no
  - name: install gem bundler
    gem: name=bundler state=latest
  - name: install gem rails
    gem: name=rails state=latest
  - name: install gem rubocop
    gem: name=rubocop state=latest
  - name: install numpy and scipy
    sudo: yes
    shell: pip3 install numpy scipy
  - name: download and unzip opencv
    shell: wget -O opencv.zip https://github.com/Itseez/opencv/archive/3.1.0.zip && unzip opencv.zip
  - name: download and unzip opencv-contrib
    shell: wget -O opencv_contrib.zip https://github.com/Itseez/opencv_contrib/archive/3.1.0.zip && unzip opencv_contrib.zip
  - name: prepare opencv build folder
    shell: cd ./opencv-3.1.0/ && mkdir build && cd build && cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D INSTALL_PYTHON_EXAMPLES=ON -D INSTALL_C_EXAMPLES=OFF -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.1.0/modules -D PYTHON_EXECUTABLE=/usr/bin/python3 -D ENABLE_PRECOMPILED_HEADERS=OFF -D BUILD_EXAMPLES=ON ..
  - name: compile and install opencv
    sudo: yes
    shell: make install && ldconfig
  - name: rename opencv so file
    sudo: yes
    shell: cd /usr/local/lib/python3.5/dist-packages/ && mv cv2.cpython-35m-x86_64-linux-gnu.so cv2.so

